server:
  port: 9003

spring:
  application:
    name: xinnengyuan-web
    index: 0
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/yibaisheng?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: dmfuck
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    enabled: true
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cms.jycms.domain

web:
  upload-path: uploadData
  imagesDir: xinnengyuan/upload
  hostName: ""

multipart:
  maxFileSize: 10Mb
  maxRequestSize: 50Mb